(() => {
  const API = String(window.CONEXA_CONFIG?.API_URL || '').replace(/\/$/, '');
  const $ = id => document.getElementById(id);
  const state = { mode:'login', user:null, communities:[], community:null, categories:[], channels:[], channel:null, socket:null, voiceStream:null, peers:new Map(), muted:false };
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function api(path, options={}) { const res=await fetch(API+path,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options}); let data={}; try{data=await res.json()}catch{} if(!res.ok)throw new Error(data.error||`Erro ${res.status}`); return data; }
  function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2600)}
  function authMode(mode){state.mode=mode;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('name-wrap').classList.toggle('hidden',mode!=='register');$('name').required=mode==='register';$('auth-title').textContent=mode==='register'?'Crie seu espaço.':'Que bom te ver de volta.';$('auth-submit').textContent=mode==='register'?'Criar conta':'Entrar';$('auth-error').textContent='';}
  document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>authMode(b.dataset.mode)));
  $('auth-form').addEventListener('submit',async e=>{e.preventDefault();$('auth-error').textContent='';const body={email:$('email').value,password:$('password').value};if(state.mode==='register')body.username=$('name').value;try{const d=await api('/api/auth/'+(state.mode==='register'?'register':'login'),{method:'POST',body:JSON.stringify(body)});state.user=d.user;await enterApp();}catch(err){$('auth-error').textContent=err.message;}});
  async function enterApp(){ $('auth').classList.add('hidden');$('workspace').classList.remove('hidden');$('user-name').textContent=state.user.username;await loadCommunities();connectSocket(); }
  async function boot(){try{const d=await api('/api/auth/me');state.user=d.user;await enterApp();}catch{$('auth').classList.remove('hidden');$('workspace').classList.add('hidden');}}
  async function logout(){try{await api('/api/auth/logout',{method:'POST',body:'{}'});}catch{}if(state.socket)state.socket.disconnect();state.user=null;state.community=null;state.channel=null;$('workspace').classList.add('hidden');$('auth').classList.remove('hidden');$('password').value='';}
  $('logout').onclick=logout;$('logout-bottom').onclick=logout;
  async function loadCommunities(){const d=await api('/api/communities');state.communities=d.communities;if(!state.communities.length){renderServers();showCommunityModal();return;}if(!state.community||!state.communities.some(c=>String(c.id)===String(state.community.id)))state.community=state.communities[0];renderServers();await loadStructure();}
  function renderServers(){ $('server-list').innerHTML=state.communities.map(c=>`<button class="server-icon ${state.community&&String(c.id)===String(state.community.id)?'selected':''}" data-id="${c.id}" title="${esc(c.name)}">${c.image_url?`<img src="${esc(c.image_url)}" alt="">`:esc(c.name.slice(0,2).toUpperCase())}</button>`).join('');document.querySelectorAll('.server-icon').forEach(b=>b.onclick=async()=>{state.community=state.communities.find(c=>String(c.id)===b.dataset.id);state.channel=null;renderServers();await loadStructure();}); }
  async function loadStructure(){if(!state.community)return; $('community-name').textContent=state.community.name;$('community-description').textContent=state.community.description||'Sua comunidade';const d=await api(`/api/communities/${state.community.id}/structure`);state.categories=d.categories;state.channels=d.channels;renderTree();if(!state.channel||!state.channels.some(c=>String(c.id)===String(state.channel.id)))state.channel=state.channels[0]||null;renderChannel();}
  function renderTree(){const uncat=state.channels.filter(c=>!c.category_id);let html='';for(const cat of state.categories){const list=state.channels.filter(c=>String(c.category_id)===String(cat.id));html+=`<div class="category"><div class="category-head"><span>⌄ ${esc(cat.name)}</span><button class="icon-btn cat-add" data-id="${cat.id}" title="Criar canal nesta categoria">＋</button></div>${list.map(channelHtml).join('')}</div>`;}if(uncat.length)html+=`<div class="category"><div class="category-head">CANAIS</div>${uncat.map(channelHtml).join('')}</div>`;$('channel-tree').innerHTML=html;document.querySelectorAll('.channel-btn').forEach(b=>b.onclick=()=>{state.channel=state.channels.find(c=>String(c.id)===b.dataset.id);renderTree();renderChannel();});document.querySelectorAll('.cat-add').forEach(b=>b.onclick=()=>showChannelModal(b.dataset.id));}
  function channelHtml(c){return `<button class="channel-btn ${state.channel&&String(state.channel.id)===String(c.id)?'active':''}" data-id="${c.id}"><span class="hash">${c.type==='voice'?'◖))':'#'}</span><span class="channel-name">${esc(c.name)}</span></button>`;}
  function renderChannel(){const c=state.channel;if(!c){$('channel-title').textContent='Sem canais';$('channel-topic').textContent='Crie um canal para começar';$('chat-view').classList.remove('hidden');$('message-form').classList.remove('hidden');$('voice-view').classList.add('hidden');return;}$('channel-title').textContent=c.name;$('channel-topic').textContent=c.topic|| (c.type==='voice'?'Canal de voz':'Converse com sua comunidade');$('channel-symbol').textContent=c.type==='voice'?'◖))':'#';const isVoice=c.type==='voice';$('chat-view').classList.toggle('hidden',isVoice);$('message-form').classList.toggle('hidden',isVoice);$('voice-view').classList.toggle('hidden',!isVoice);if(isVoice){$('voice-title').textContent=c.name;$('voice-members').innerHTML='<div class="voice-member">🎧 Você ainda não entrou</div>';$('join-voice').disabled=false;$('leave-voice').disabled=true;$('mute-voice').disabled=true;}else loadMessages(c.id).catch(e=>toast(e.message));if(state.socket)state.socket.emit('join-channel',String(c.id));}
  async function loadMessages(id){const d=await api(`/api/channels/${id}/messages`);$('messages').innerHTML=d.messages.map(messageHtml).join('');$('chat-view').scrollTop=$('chat-view').scrollHeight;}
  function messageHtml(m){const dt=new Date(m.created_at);return `<article class="message"><div class="avatar">${esc((m.username||'?').slice(0,2).toUpperCase())}</div><div class="message-body"><div class="message-head"><b>${esc(m.username)}</b><time>${isNaN(dt)?'':dt.toLocaleString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time></div><p>${esc(m.content)}</p></div></article>`;}
  $('message-form').addEventListener('submit',async e=>{e.preventDefault();const content=$('message-input').value.trim();if(!content||!state.channel||state.channel.type!=='text')return;const input=$('message-input');input.value='';try{const d=await api(`/api/channels/${state.channel.id}/messages`,{method:'POST',body:JSON.stringify({content})});if(!$('messages').querySelector(`[data-message-id="${d.message.id}"]`)){$('messages').insertAdjacentHTML('beforeend',messageHtml(d.message));$('chat-view').scrollTop=$('chat-view').scrollHeight;}}catch(err){input.value=content;toast(err.message);}});
  function connectSocket(){if(!window.io){$('connection').textContent='● chat via API';return;}if(state.socket)state.socket.disconnect();state.socket=window.io(API,{withCredentials:true,transports:['websocket','polling']});state.socket.on('connect',()=>$('connection').textContent='● online');state.socket.on('disconnect',()=>$('connection').textContent='● reconectando');state.socket.on('message',m=>{if(state.channel&&String(state.channel.id)===String(m.channelId)&&!$('messages').innerHTML.includes(`>${esc(m.content)}<`)){$('messages').insertAdjacentHTML('beforeend',messageHtml(m));$('chat-view').scrollTop=$('chat-view').scrollHeight;}});}
  // Modal helpers
  function showModal(title,fields,onSubmit){$('modal-title').textContent=title;$('modal-fields').innerHTML=fields;$('modal-error').textContent='';$('modal').classList.remove('hidden');$('modal-form').onsubmit=async e=>{e.preventDefault();const values={};new FormData(e.currentTarget).forEach((v,k)=>values[k]=v);try{await onSubmit(values);$('modal').classList.add('hidden');}catch(err){$('modal-error').textContent=err.message;}};}
  $('modal-close').onclick=()=>$('modal').classList.add('hidden');$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.add('hidden')};
  function showCommunityModal(edit=false){const c=edit?state.community:null;showModal(edit?'Editar comunidade':'Criar comunidade',`<label>Nome<input name="name" required minlength="2" maxlength="80" value="${esc(c?.name||'')}" placeholder="Clube dos amigos"></label><label>Descrição<textarea name="description" maxlength="240" placeholder="Sobre esta comunidade">${esc(c?.description||'')}</textarea></label><label>URL da imagem (HTTPS)<input name="imageUrl" type="url" value="${esc(c?.image_url||'')}" placeholder="https://.../capa.png"></label>`,async v=>{if(edit){const d=await api(`/api/communities/${c.id}`,{method:'PATCH',body:JSON.stringify(v)});state.community=d.community;state.communities=state.communities.map(x=>String(x.id)===String(c.id)?d.community:x);}else{const d=await api('/api/communities',{method:'POST',body:JSON.stringify(v)});state.communities.push(d.community);state.community=d.community;state.channel=null;}renderServers();await loadStructure();});}
  function showCategoryModal(){if(!state.community)return showCommunityModal();showModal('Criar categoria','<label>Nome da categoria<input name="name" required maxlength="80" placeholder="Jogos, conversas…"></label>',async v=>{await api(`/api/communities/${state.community.id}/categories`,{method:'POST',body:JSON.stringify(v)});await loadStructure();});}
  function showChannelModal(categoryId=''){if(!state.community)return showCommunityModal();const opts=state.categories.map(c=>`<option value="${c.id}" ${String(c.id)===String(categoryId)?'selected':''}>${esc(c.name)}</option>`).join('');showModal('Criar canal',`<label>Nome do canal<input name="name" required maxlength="80" placeholder="geral"></label><label>Tipo<select name="type"><option value="text"># Canal de texto</option><option value="voice">◖)) Canal de voz</option></select></label><label>Categoria<select name="categoryId"><option value="">Sem categoria</option>${opts}</select></label><label>Tópico (opcional)<input name="topic" maxlength="240" placeholder="Sobre o que é este canal?"></label>`,async v=>{await api(`/api/communities/${state.community.id}/channels`,{method:'POST',body:JSON.stringify(v)});await loadStructure();});}
  $('new-community').onclick=()=>showCommunityModal();$('edit-community').onclick=()=>showCommunityModal(true);$('add-category').onclick=showCategoryModal;$('add-channel').onclick=()=>showChannelModal();
  // Basic voice-room controls. Full peer negotiation/STUN-TURN is intentionally not represented as production-ready.
  $('join-voice').onclick=async()=>{if(!state.channel||!state.socket)return toast('Conexão de voz indisponível.');try{state.voiceStream=await navigator.mediaDevices.getUserMedia({audio:true});state.socket.emit('join-voice',String(state.channel.id));$('join-voice').disabled=true;$('leave-voice').disabled=false;$('mute-voice').disabled=false;$('voice-members').innerHTML=`<div class="voice-member">🎙 ${esc(state.user.username)} · conectado localmente</div>`;toast('Microfone autorizado. A negociação entre participantes ainda precisa ser concluída.');}catch(e){toast('Não foi possível acessar o microfone: '+e.message);}};
  $('mute-voice').onclick=()=>{if(!state.voiceStream)return;state.muted=!state.muted;state.voiceStream.getAudioTracks().forEach(t=>t.enabled=!state.muted);$('mute-voice').textContent=state.muted?'Ativar microfone':'Desativar microfone';};
  $('leave-voice').onclick=()=>{if(state.socket)state.socket.emit('leave-voice');if(state.voiceStream)state.voiceStream.getTracks().forEach(t=>t.stop());state.voiceStream=null;state.muted=false;$('join-voice').disabled=false;$('leave-voice').disabled=true;$('mute-voice').disabled=true;$('mute-voice').textContent='Microfone desligado';$('voice-members').innerHTML='<div class="voice-member">🎧 Você saiu da sala</div>';};
  $('attach').onclick=()=>toast('Envio de anexos ainda não implementado.');
  // Socket.IO is loaded dynamically from the backend's public endpoint; no external frontend build step is needed.
  const script=document.createElement('script');script.src=API+'/socket.io/socket.io.js';script.onload=()=>{if(state.user)connectSocket();};script.onerror=()=>{};document.head.appendChild(script);
  boot().catch(err=>toast(err.message));
})();
