(() => {
  const API = String(window.CONEXA_CONFIG?.API_URL || '').replace(/\/$/, '');
  const $ = id => document.getElementById(id);
  const state = { mode:'login', user:null, communities:[], community:null, categories:[], channels:[], channel:null, socket:null, voiceStream:null, peers:new Map(), muted:false, screenStream:null, screenTrack:null, speakingTimers:new Map() };
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function api(path, options={}) { const res=await fetch(API+path,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options}); let data={}; try{data=await res.json()}catch{} if(!res.ok)throw new Error(data.error||`Erro ${res.status}`); return data; }
  function toast(message){const el=$('toast');if(!el)return;el.textContent=message;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),3000)}
  function authMode(mode){state.mode=mode;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('name-wrap').classList.toggle('hidden',mode!=='register');$('name').required=mode==='register';$('auth-title').textContent=mode==='register'?'Crie seu espaço.':'Que bom te ver de volta.';$('auth-submit').textContent=mode==='register'?'Criar conta':'Entrar';$('auth-error').textContent='';}
  document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>authMode(b.dataset.mode)));
  $('auth-form').addEventListener('submit',async e=>{e.preventDefault();$('auth-error').textContent='';const body={email:$('email').value,password:$('password').value};if(state.mode==='register')body.username=$('name').value;try{const d=await api('/api/auth/'+(state.mode==='register'?'register':'login'),{method:'POST',body:JSON.stringify(body)});state.user=d.user;await enterApp();}catch(err){$('auth-error').textContent=err.message;}});
  async function enterApp(){ $('auth').classList.add('hidden');$('workspace').classList.remove('hidden');$('user-name').textContent=state.user.username;injectEnhancements();await loadCommunities();connectSocket();loadProfile().catch(()=>{}); }
  async function boot(){try{const d=await api('/api/auth/me');state.user=d.user;await enterApp();}catch{$('auth').classList.remove('hidden');$('workspace').classList.add('hidden');}}
  async function logout(){leaveVoice();try{await api('/api/auth/logout',{method:'POST',body:'{}'});}catch{}if(state.socket)state.socket.disconnect();state.user=null;state.community=null;state.channel=null;$('workspace').classList.add('hidden');$('auth').classList.remove('hidden');$('password').value='';}
  $('logout').onclick=logout;$('logout-bottom').onclick=logout;
  async function loadCommunities(){const d=await api('/api/communities');state.communities=d.communities;if(!state.communities.length){renderServers();showCommunityModal();return;}if(!state.community||!state.communities.some(c=>String(c.id)===String(state.community.id)))state.community=state.communities[0];renderServers();await loadStructure();}
  function renderServers(){ $('server-list').innerHTML=state.communities.map(c=>`<button class="server-icon ${state.community&&String(c.id)===String(state.community.id)?'selected':''}" data-id="${c.id}" title="${esc(c.name)}">${c.image_url?`<img src="${esc(c.image_url)}" alt="">`:esc(c.name.slice(0,2).toUpperCase())}</button>`).join('');document.querySelectorAll('.server-icon').forEach(b=>b.onclick=async()=>{state.community=state.communities.find(c=>String(c.id)===b.dataset.id);state.channel=null;renderServers();await loadStructure();}); }
  async function loadStructure(){if(!state.community)return; $('community-name').textContent=state.community.name;$('community-description').textContent=state.community.description||'Sua comunidade';const d=await api(`/api/communities/${state.community.id}/structure`);state.categories=d.categories;state.channels=d.channels;renderTree();if(!state.channel||!state.channels.some(c=>String(c.id)===String(state.channel.id)))state.channel=state.channels[0]||null;renderChannel();}
  function renderTree(){const uncat=state.channels.filter(c=>!c.category_id);let html='';for(const cat of state.categories){const list=state.channels.filter(c=>String(c.category_id)===String(cat.id));html+=`<div class="category"><div class="category-head"><span>⌄ ${esc(cat.name)}</span><button class="icon-btn cat-add" data-id="${cat.id}" title="Criar canal nesta categoria">＋</button></div>${list.map(channelHtml).join('')}</div>`;}if(uncat.length)html+=`<div class="category"><div class="category-head">CANAIS</div>${uncat.map(channelHtml).join('')}</div>`;$('channel-tree').innerHTML=html;document.querySelectorAll('.channel-btn').forEach(b=>b.onclick=()=>{if(state.channel?.type==='voice')leaveVoice();state.channel=state.channels.find(c=>String(c.id)===b.dataset.id);renderTree();renderChannel();});document.querySelectorAll('.cat-add').forEach(b=>b.onclick=()=>showChannelModal(b.dataset.id));}
  function channelHtml(c){return `<button class="channel-btn ${state.channel&&String(c.id)===String(state.channel.id)?'active':''}" data-id="${c.id}"><span class="hash">${c.type==='voice'?'◖))':'#'}</span><span class="channel-name">${esc(c.name)}</span></button>`;}
  function renderChannel(){const c=state.channel;if(!c){$('channel-title').textContent='Sem canais';$('channel-topic').textContent='Crie um canal para começar';$('chat-view').classList.remove('hidden');$('message-form').classList.remove('hidden');$('voice-view').classList.add('hidden');return;}$('channel-title').textContent=c.name;$('channel-topic').textContent=c.topic|| (c.type==='voice'?'Canal de voz':'Converse com sua comunidade');$('channel-symbol').textContent=c.type==='voice'?'◖))':'#';const isVoice=c.type==='voice';$('chat-view').classList.toggle('hidden',isVoice);$('message-form').classList.toggle('hidden',isVoice);$('voice-view').classList.toggle('hidden',!isVoice);if(isVoice){$('voice-title').textContent=c.name;$('voice-members').innerHTML='<div class="voice-member">Entre na sala para conversar</div>';if($('voice-tools'))$('voice-tools').classList.remove('hidden');$('join-voice').disabled=false;$('leave-voice').disabled=true;$('mute-voice').disabled=true;}else{if($('voice-tools'))$('voice-tools').classList.add('hidden');loadMessages(c.id).catch(e=>toast(e.message));}if(state.socket&&state.socket.connected&&c.type==='text')state.socket.emit('join-channel',String(c.id));}
  async function loadMessages(id){const d=await api(`/api/channels/${id}/messages`);if(!state.channel||String(state.channel.id)!==String(id))return;$('messages').innerHTML=d.messages.map(messageHtml).join('');$('chat-view').scrollTop=$('chat-view').scrollHeight;}
  function messageHtml(m){const dt=new Date(m.created_at);return `<article class="message" data-message-id="${esc(m.id)}"><img class="avatar message-avatar" src="${esc(m.avatar_url||'')}" alt="" onerror="this.style.display='none'"><div class="avatar fallback-avatar">${esc((m.username||'?').slice(0,2).toUpperCase())}</div><div class="message-body"><div class="message-head"><b>${esc(m.username)}</b><time>${isNaN(dt)?'':dt.toLocaleString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time></div><p>${esc(m.content)}</p></div></article>`;}
  function appendMessage(m){if(!state.channel||String(state.channel.id)!==String(m.channelId))return;if($('messages').querySelector(`[data-message-id="${CSS.escape(String(m.id))}"]`))return;$('messages').insertAdjacentHTML('beforeend',messageHtml(m));$('chat-view').scrollTop=$('chat-view').scrollHeight;}
  $('message-form').addEventListener('submit',async e=>{e.preventDefault();const content=$('message-input').value.trim();if(!content||!state.channel||state.channel.type!=='text')return;const input=$('message-input');input.value='';try{const d=await api(`/api/channels/${state.channel.id}/messages`,{method:'POST',body:JSON.stringify({content})});appendMessage({...d.message,channelId:String(state.channel.id)});}catch(err){input.value=content;toast(err.message);}});
  function connectSocket(){if(!window.io){$('connection').textContent='● chat via API';return;}if(state.socket)state.socket.disconnect();state.socket=window.io(API,{withCredentials:true,transports:['websocket','polling'],reconnection:true});state.socket.on('connect',()=>{$('connection').textContent='● online';if(state.channel&&state.channel.type==='text')state.socket.emit('join-channel',String(state.channel.id));});state.socket.on('disconnect',()=>$('connection').textContent='● reconectando');state.socket.on('message',m=>appendMessage(m));state.socket.on('voice-member-joined',async p=>{if(!state.voiceStream||!state.channel)return;await createPeer(p.socketId,true);renderVoiceMembers();});state.socket.on('voice-peers',async ids=>{for(const id of ids||[])await createPeer(id,false);renderVoiceMembers();});state.socket.on('voice-member-left',p=>{const pc=state.peers.get(p.socketId);if(pc)pc.close();state.peers.delete(p.socketId);renderVoiceMembers();});state.socket.on('voice-signal',async p=>{try{let pc=state.peers.get(p.from);if(!pc)pc=await createPeer(p.from,false);const s=p.signal;if(s.description){await pc.setRemoteDescription(s.description);if(s.description.type==='offer'){await pc.setLocalDescription(await pc.createAnswer());sendSignal(p.from,{description:pc.localDescription});}}else if(s.candidate)await pc.addIceCandidate(s.candidate);}catch(e){console.warn('WebRTC signaling',e);}});}
  function sendSignal(to,signal){if(state.socket&&state.channel)state.socket.emit('voice-signal',{channelId:String(state.channel.id),to,signal});}
  async function createPeer(id,offer){if(state.peers.has(id))return state.peers.get(id);const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun.cloudflare.com:3478'}]});state.peers.set(id,pc);for(const track of state.voiceStream?.getTracks()||[])pc.addTrack(track,state.voiceStream);if(state.screenTrack)pc.addTrack(state.screenTrack,state.screenStream);pc.onicecandidate=e=>{if(e.candidate)sendSignal(id,{candidate:e.candidate});};pc.ontrack=e=>{let audio=document.getElementById('remote-'+id);if(!audio){audio=document.createElement('audio');audio.id='remote-'+id;audio.autoplay=true;audio.playsInline=true;audio.hidden=true;document.body.appendChild(audio);}audio.srcObject=e.streams[0];monitorSpeaking(e.streams[0],id);};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState)){pc.close();state.peers.delete(id);renderVoiceMembers();}};if(offer){await pc.setLocalDescription(await pc.createOffer());sendSignal(id,{description:pc.localDescription});}return pc;}
  function renderVoiceMembers(){if(!$('voice-members'))return;const count=state.peers.size+(state.voiceStream?1:0);$('voice-members').innerHTML=(state.voiceStream?`<div class="voice-member" id="voice-self"><img class="voice-avatar" src="${esc(state.user?.avatar_url||'')}" onerror="this.style.display='none'"><span>${esc(state.user?.username||'Você')} <small>você</small></span></div>`:'')+Array.from(state.peers.keys()).map(id=>`<div class="voice-member" id="voice-${esc(id)}"><div class="voice-avatar voice-placeholder">${esc((id||'?').slice(0,2))}</div><span>Participante</span></div>`).join('')+(!count?'<div class="voice-member">Ninguém na sala ainda</div>':'');}
  function monitorSpeaking(stream,id){try{const ctx=new (window.AudioContext||window.webkitAudioContext)();const analyser=ctx.createAnalyser();analyser.fftSize=512;ctx.createMediaStreamSource(stream).connect(analyser);const data=new Uint8Array(analyser.frequencyBinCount);const check=()=>{if(!state.peers.has(id))return;analyser.getByteTimeDomainData(data);let sum=0;for(const n of data)sum+=(n-128)*(n-128);const speaking=Math.sqrt(sum/data.length)>7;const el=document.getElementById('voice-'+id);if(el)el.classList.toggle('speaking',speaking);requestAnimationFrame(check);};check();}catch{}}
  function monitorLocalSpeaking(){if(!state.voiceStream)return;try{const ctx=new (window.AudioContext||window.webkitAudioContext)();const analyser=ctx.createAnalyser();analyser.fftSize=512;ctx.createMediaStreamSource(state.voiceStream).connect(analyser);const data=new Uint8Array(analyser.frequencyBinCount);const check=()=>{if(!state.voiceStream)return;analyser.getByteTimeDomainData(data);let sum=0;for(const n of data)sum+=(n-128)*(n-128);$('voice-self')?.classList.toggle('speaking',Math.sqrt(sum/data.length)>7);requestAnimationFrame(check);};check();}catch{}}
  $('join-voice').onclick=async()=>{if(!state.channel||!state.socket)return toast('Conexão de voz indisponível.');try{state.voiceStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});state.socket.emit('join-voice',String(state.channel.id));$('join-voice').disabled=true;$('leave-voice').disabled=false;$('mute-voice').disabled=false;renderVoiceMembers();monitorLocalSpeaking();toast('Você entrou na sala de voz.');}catch(e){toast('Não foi possível acessar o microfone: '+e.message);}};
  $('mute-voice').onclick=()=>{if(!state.voiceStream)return;state.muted=!state.muted;state.voiceStream.getAudioTracks().forEach(t=>t.enabled=!state.muted);$('mute-voice').textContent=state.muted?'Ativar microfone':'Desativar microfone';};
  function leaveVoice(){if(state.socket)state.socket.emit('leave-voice');for(const pc of state.peers.values())pc.close();state.peers.clear();if(state.voiceStream)state.voiceStream.getTracks().forEach(t=>t.stop());state.voiceStream=null;state.muted=false;document.querySelectorAll('audio[id^="remote-"]').forEach(a=>a.remove());if($('join-voice'))$('join-voice').disabled=false;if($('leave-voice'))$('leave-voice').disabled=true;if($('mute-voice')){$('mute-voice').disabled=true;$('mute-voice').textContent='Desativar microfone';}if($('voice-members'))$('voice-members').innerHTML='<div class="voice-member">Você saiu da sala</div>';stopScreenShare();}
  $('leave-voice').onclick=leaveVoice;
  // Screen share: adaptive presets trade sharpness for bandwidth. Actual network quality is browser/network dependent.
  async function startScreenShare(){if(!navigator.mediaDevices?.getDisplayMedia)return toast('Seu navegador não permite compartilhar tela.');try{const preset=$('share-quality')?.value||'balanced';const settings={low:{width:640,height:360,frameRate:10},balanced:{width:1280,height:720,frameRate:15},high:{width:1920,height:1080,frameRate:30}}[preset];state.screenStream=await navigator.mediaDevices.getDisplayMedia({video:{width:{ideal:settings.width},height:{ideal:settings.height},frameRate:{ideal:settings.frameRate,max:settings.frameRate}},audio:false});state.screenTrack=state.screenStream.getVideoTracks()[0];state.screenTrack.contentHint='detail';for(const pc of state.peers.values()){const sender=pc.getSenders().find(s=>s.track?.kind==='video');if(sender)await sender.replaceTrack(state.screenTrack);else pc.addTrack(state.screenTrack,state.screenStream);}state.screenTrack.onended=stopScreenShare;$('share-screen').textContent='Parar compartilhamento';$('share-screen').classList.add('active');showScreenPreview();toast('Compartilhamento iniciado.');}catch(e){if(e.name!=='NotAllowedError')toast('Não foi possível compartilhar: '+e.message);}}
  function showScreenPreview(){let v=$('screen-preview');if(!v){v=document.createElement('video');v.id='screen-preview';v.autoplay=true;v.muted=true;v.playsInline=true;v.className='screen-preview';$('voice-view').appendChild(v);}v.srcObject=state.screenStream;v.classList.remove('hidden');}
  async function stopScreenShare(){if(!state.screenStream)return;for(const pc of state.peers.values()){const sender=pc.getSenders().find(s=>s.track===state.screenTrack);if(sender)await sender.replaceTrack(null).catch(()=>{});}state.screenStream.getTracks().forEach(t=>t.stop());state.screenStream=null;state.screenTrack=null;$('share-screen')?.classList.remove('active');if($('share-screen'))$('share-screen').textContent='Compartilhar tela';$('screen-preview')?.classList.add('hidden');}
  function injectEnhancements(){if(!$('profile-open')){const top=$('community-name')?.parentElement;const b=document.createElement('button');b.id='profile-open';b.className='secondary-button';b.textContent='Perfil';b.onclick=showProfileModal;top?.appendChild(b);}if(!$('invite-open')){const top=$('community-name')?.parentElement;const b=document.createElement('button');b.id='invite-open';b.className='secondary-button';b.textContent='＋ Convidar';b.onclick=showInviteModal;top?.appendChild(b);}if(!$('voice-tools')){const tools=document.createElement('div');tools.id='voice-tools';tools.className='voice-tools hidden';tools.innerHTML='<label>Qualidade da tela <select id="share-quality"><option value="low">Economia de banda · 360p / 10 FPS</option><option value="balanced" selected>Equilibrada · até 720p / 15 FPS</option><option value="high">Alta · até 1080p / 30 FPS</option></select></label><button id="share-screen" class="secondary-button">Compartilhar tela</button>'; $('voice-view')?.appendChild(tools);$('share-screen').onclick=()=>state.screenStream?stopScreenShare():startScreenShare();}if(!$('profile-avatar-small')){const userBox=$('user-name')?.parentElement;const img=document.createElement('img');img.id='profile-avatar-small';img.className='profile-avatar-small';img.alt='';userBox?.prepend(img);}}
  async function loadProfile(){const d=await api('/api/users/me');state.user={...state.user,...d.user};$('user-name').textContent=state.user.username;$('profile-avatar-small').src=state.user.avatar_url||'';}
  function showProfileModal(){const u=state.user||{};showModal('Seu perfil',`<div class="profile-modal-head"><img class="profile-preview" src="${esc(u.avatar_url||'')}" onerror="this.style.display='none'"><p>Personalize sua foto e sua descrição.</p></div><label>Nome de usuário<input name="username" minlength="3" maxlength="32" required value="${esc(u.username||'')}"></label><label>Descrição<textarea name="description" maxlength="240" placeholder="Um pouco sobre você">${esc(u.description||'')}</textarea></label><label>URL da foto de perfil<input name="avatarUrl" type="url" value="${esc(u.avatar_url||'')}" placeholder="https://.../avatar.png"></label>`,async v=>{const d=await api('/api/users/me',{method:'PATCH',body:JSON.stringify(v)});state.user={...state.user,...d.user};$('user-name').textContent=state.user.username;$('profile-avatar-small').src=state.user.avatar_url||'';toast('Perfil atualizado.');});}
  async function showInviteModal(){if(!state.community)return toast('Selecione uma comunidade primeiro.');showModal('Convidar para a comunidade',`<p>Gere um link para compartilhar com seus amigos.</p><label>Link do convite<input id="invite-link" name="inviteLink" readonly placeholder="Clique em Gerar convite"></label><button type="button" class="secondary-button" id="generate-invite">Gerar convite</button><button type="button" class="secondary-button" id="copy-invite">Copiar link</button>`,async()=>{});$('generate-invite').onclick=async()=>{try{const d=await api(`/api/communities/${state.community.id}/invites`,{method:'POST',body:JSON.stringify({})});$('invite-link').value=d.url||`${location.origin}${location.pathname}?invite=${encodeURIComponent(d.token)}`;}catch(e){toast('Convites não estão ativos no backend: '+e.message);}};$('copy-invite').onclick=async()=>{const val=$('invite-link').value;if(!val)return toast('Gere um convite primeiro.');try{await navigator.clipboard.writeText(val);toast('Link copiado!');}catch{ $('invite-link').select();document.execCommand('copy');toast('Link copiado!');}};}
  // Modal helpers
  function showModal(title,fields,onSubmit){$('modal-title').textContent=title;$('modal-fields').innerHTML=fields;$('modal-error').textContent='';$('modal').classList.remove('hidden');$('modal-form').onsubmit=async e=>{e.preventDefault();const values={};new FormData(e.currentTarget).forEach((v,k)=>values[k]=v);try{await onSubmit(values);$('modal').classList.add('hidden');}catch(err){$('modal-error').textContent=err.message;}};}
  $('modal-close').onclick=()=>$('modal').classList.add('hidden');$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.add('hidden')};
  function showCommunityModal(edit=false){const c=edit?state.community:null;showModal(edit?'Editar comunidade':'Criar comunidade',`<label>Nome<input name="name" required minlength="2" maxlength="80" value="${esc(c?.name||'')}" placeholder="Clube dos amigos"></label><label>Descrição<textarea name="description" maxlength="240" placeholder="Sobre esta comunidade">${esc(c?.description||'')}</textarea></label><label>URL da imagem (HTTPS)<input name="imageUrl" type="url" value="${esc(c?.image_url||'')}" placeholder="https://.../capa.png"></label>`,async v=>{if(edit){const d=await api(`/api/communities/${c.id}`,{method:'PATCH',body:JSON.stringify(v)});state.community=d.community;state.communities=state.communities.map(x=>String(x.id)===String(c.id)?d.community:x);}else{const d=await api('/api/communities',{method:'POST',body:JSON.stringify(v)});state.communities.push(d.community);state.community=d.community;state.channel=null;}renderServers();await loadStructure();});}
  function showCategoryModal(){if(!state.community)return showCommunityModal();showModal('Criar categoria','<label>Nome da categoria<input name="name" required maxlength="80" placeholder="Jogos, conversas…"></label>',async v=>{await api(`/api/communities/${state.community.id}/categories`,{method:'POST',body:JSON.stringify(v)});await loadStructure();});}
  function showChannelModal(categoryId=''){if(!state.community)return showCommunityModal();const opts=state.categories.map(c=>`<option value="${c.id}" ${String(c.id)===String(categoryId)?'selected':''}>${esc(c.name)}</option>`).join('');showModal('Criar canal',`<label>Nome do canal<input name="name" required maxlength="80" placeholder="geral"></label><label>Tipo<select name="type"><option value="text"># Canal de texto</option><option value="voice">◖)) Canal de voz</option></select></label><label>Categoria<select name="categoryId"><option value="">Sem categoria</option>${opts}</select></label><label>Tópico (opcional)<input name="topic" maxlength="240" placeholder="Sobre o que é este canal?"></label>`,async v=>{await api(`/api/communities/${state.community.id}/channels`,{method:'POST',body:JSON.stringify(v)});await loadStructure();});}
  $('new-community').onclick=()=>showCommunityModal();$('edit-community').onclick=()=>showCommunityModal(true);$('add-category').onclick=showCategoryModal;$('add-channel').onclick=()=>showChannelModal();$('attach').onclick=()=>toast('Envio de anexos ainda não implementado.');
  const script=document.createElement('script');script.src=API+'/socket.io/socket.io.js';script.onload=()=>{if(state.user)connectSocket();};script.onerror=()=>{};document.head.appendChild(script);
  boot().catch(err=>toast(err.message));
})();
