(() => {
  const API = String(window.CONEXA_CONFIG?.API_URL || '').replace(/\/$/, '');
  const state = { mode:'login', user:null, communities:[], community:null, categories:[], channels:[], channel:null, socket:null, voiceStream:null, peers:new Map(), peerUsers:new Map(), muted:false, voiceChannel:null, audioContext:null, speakingTimer:null, inviteToken:new URLSearchParams(location.search).get('invite') };
  const $ = id => document.getElementById(id);
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const avatarHtml = (url, name, cls='avatar') => url ? `<img class="${cls} avatar-image" src="${esc(url)}" alt="Foto de ${esc(name||'usuário')}" referrerpolicy="no-referrer">` : `<span class="${cls}">${esc(String(name||'?').slice(0,2).toUpperCase())}</span>`;
  async function api(path, options={}) { let res; try { res=await fetch(API+path,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options}); } catch(e) { throw new Error('Não foi possível conectar à API. Confira a conexão e a URL do backend.'); } let data={}; try{data=await res.json()}catch{} if(!res.ok)throw new Error(data.error||`Erro ${res.status}`); return data; }
  function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),3200)}
  function authMode(mode){state.mode=mode;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('name-wrap').classList.toggle('hidden',mode!=='register');$('name').required=mode==='register';$('auth-title').textContent=mode==='register'?'Crie seu espaço.':'Que bom te ver de volta.';$('auth-submit').textContent=mode==='register'?'Criar conta':'Entrar';$('auth-error').textContent='';}
  document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>authMode(b.dataset.mode)));
  $('auth-form').addEventListener('submit',async e=>{e.preventDefault();$('auth-error').textContent='';const body={email:$('email').value,password:$('password').value};if(state.mode==='register')body.username=$('name').value;try{const d=await api('/api/auth/'+(state.mode==='register'?'register':'login'),{method:'POST',body:JSON.stringify(body)});state.user=d.user;await enterApp();}catch(err){$('auth-error').textContent=err.message;}});
  async function enterApp(){ $('auth').classList.add('hidden');$('workspace').classList.remove('hidden');renderProfile();await loadCommunities();connectSocket();if(state.inviteToken)await acceptInvite(state.inviteToken); }
  async function boot(){try{const d=await api('/api/auth/me');state.user=d.user;await enterApp();}catch{$('auth').classList.remove('hidden');$('workspace').classList.add('hidden');if(state.inviteToken){authMode('login');toast('Entre ou crie uma conta para aceitar o convite.');}}}
  async function logout(){leaveVoice();try{await api('/api/auth/logout',{method:'POST',body:'{}'});}catch{}if(state.socket)state.socket.disconnect();state.user=null;state.community=null;state.channel=null;$('workspace').classList.add('hidden');$('auth').classList.remove('hidden');$('password').value='';}
  $('logout').onclick=logout;$('logout-bottom').onclick=logout;
  function renderProfile(){if(!state.user)return;$('user-name').textContent=state.user.username;const old=document.querySelector('.user-panel .profile-avatar');if(old){old.outerHTML=avatarHtml(state.user.avatar_url,state.user.username,'avatar profile-avatar');const el=document.querySelector('.user-panel .profile-avatar');if(el)el.onclick=showProfileModal;}}
  async function loadCommunities(){const d=await api('/api/communities');state.communities=d.communities;if(!state.communities.length){state.community=null;renderServers();if(!state.inviteToken)showCommunityModal();return;}if(!state.community||!state.communities.some(c=>String(c.id)===String(state.community.id)))state.community=state.communities[0];renderServers();await loadStructure();}
  function renderServers(){ $('server-list').innerHTML=state.communities.map(c=>`<button class="server-icon ${state.community&&String(c.id)===String(state.community.id)?'selected':''}" data-id="${c.id}" title="${esc(c.name)}">${c.image_url?`<img src="${esc(c.image_url)}" alt="">`:esc(c.name.slice(0,2).toUpperCase())}</button>`).join('');document.querySelectorAll('.server-icon').forEach(b=>b.onclick=async()=>{if(state.voiceChannel)leaveVoice();state.community=state.communities.find(c=>String(c.id)===b.dataset.id);state.channel=null;renderServers();await loadStructure();}); }
  async function loadStructure(){if(!state.community)return; $('community-name').textContent=state.community.name;$('community-description').textContent=state.community.description||'Sua comunidade';const d=await api(`/api/communities/${state.community.id}/structure`);state.categories=d.categories;state.channels=d.channels;renderTree();if(!state.channel||!state.channels.some(c=>String(c.id)===String(state.channel.id)))state.channel=state.channels[0]||null;renderChannel();}
  function renderTree(){const uncat=state.channels.filter(c=>!c.category_id);let html='';for(const cat of state.categories){const list=state.channels.filter(c=>String(c.category_id)===String(cat.id));html+=`<div class="category"><div class="category-head"><span>⌄ ${esc(cat.name)}</span><button class="icon-btn cat-add" data-id="${cat.id}" title="Criar canal nesta categoria">＋</button></div>${list.map(channelHtml).join('')}</div>`;}if(uncat.length)html+=`<div class="category"><div class="category-head">CANAIS</div>${uncat.map(channelHtml).join('')}</div>`;$('channel-tree').innerHTML=html;document.querySelectorAll('.channel-btn').forEach(b=>b.onclick=()=>{if(state.voiceChannel)leaveVoice();state.channel=state.channels.find(c=>String(c.id)===b.dataset.id);renderTree();renderChannel();});document.querySelectorAll('.cat-add').forEach(b=>b.onclick=()=>showChannelModal(b.dataset.id));}
  function channelHtml(c){return `<button class="channel-btn ${state.channel&&String(state.channel.id)===String(c.id)?'active':''}" data-id="${c.id}"><span class="hash">${c.type==='voice'?'◖))':'#'}</span><span class="channel-name">${esc(c.name)}</span></button>`;}
  function renderChannel(){const c=state.channel;if(!c){$('channel-title').textContent='Sem canais';$('channel-topic').textContent='Crie um canal para começar';$('chat-view').classList.remove('hidden');$('message-form').classList.remove('hidden');$('voice-view').classList.add('hidden');return;}$('channel-title').textContent=c.name;$('channel-topic').textContent=c.topic|| (c.type==='voice'?'Canal de voz':'Converse com sua comunidade');$('channel-symbol').textContent=c.type==='voice'?'◖))':'#';const isVoice=c.type==='voice';$('chat-view').classList.toggle('hidden',isVoice);$('message-form').classList.toggle('hidden',isVoice);$('voice-view').classList.toggle('hidden',!isVoice);if(isVoice){$('voice-title').textContent=c.name;if(!state.voiceChannel)$('voice-members').innerHTML='<div class="voice-empty">Entre no canal para conversar por voz.</div>';$('join-voice').disabled=!!state.voiceChannel;$('leave-voice').disabled=!state.voiceChannel;$('mute-voice').disabled=!state.voiceChannel;}else loadMessages(c.id).catch(e=>toast(e.message));if(state.socket)state.socket.emit('join-channel',String(c.id));}
  async function loadMessages(id){const d=await api(`/api/channels/${id}/messages`);$('messages').innerHTML=d.messages.map(messageHtml).join('');$('chat-view').scrollTop=$('chat-view').scrollHeight;}
  function messageHtml(m){const dt=new Date(m.created_at);return `<article class="message" data-message-id="${esc(m.id)}">${avatarHtml(m.avatar_url,m.username)}<div class="message-body"><div class="message-head"><b>${esc(m.username)}</b><time>${isNaN(dt)?'':dt.toLocaleString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time></div><p>${esc(m.content)}</p></div></article>`;}
  $('message-form').addEventListener('submit',async e=>{e.preventDefault();const content=$('message-input').value.trim();if(!content||!state.channel||state.channel.type!=='text')return;const input=$('message-input');input.value='';try{const d=await api(`/api/channels/${state.channel.id}/messages`,{method:'POST',body:JSON.stringify({content})});if(!$('messages').querySelector(`[data-message-id="${d.message.id}"]`)){$('messages').insertAdjacentHTML('beforeend',messageHtml(d.message));$('chat-view').scrollTop=$('chat-view').scrollHeight;}}catch(err){input.value=content;toast(err.message);}});
  function connectSocket(){if(!window.io){$('connection').textContent='● chat via API';return;}if(state.socket)state.socket.disconnect();state.socket=window.io(API,{withCredentials:true,transports:['websocket','polling']});state.socket.on('connect',()=>$('connection').textContent='● online');state.socket.on('disconnect',()=>$('connection').textContent='● reconectando');state.socket.on('message',m=>{if(state.channel&&String(state.channel.id)===String(m.channelId)&&!$('messages').querySelector(`[data-message-id="${m.id}"]`)){$('messages').insertAdjacentHTML('beforeend',messageHtml(m));$('chat-view').scrollTop=$('chat-view').scrollHeight;}});state.socket.on('voice-peers',async peers=>{for(const id of peers)await makeOffer(id);});state.socket.on('voice-member-joined',async d=>{state.peerUsers.set(d.socketId,d.user);renderVoiceMembers();});state.socket.on('voice-member-left',d=>{removePeer(d.socketId);});state.socket.on('voice-signal',handleVoiceSignal);}
  // Modal helpers
  function showModal(title,fields,onSubmit){$('modal-title').textContent=title;$('modal-fields').innerHTML=fields;$('modal-error').textContent='';$('modal').classList.remove('hidden');$('modal-form').onsubmit=async e=>{e.preventDefault();const values={};new FormData(e.currentTarget).forEach((v,k)=>values[k]=v);try{await onSubmit(values);$('modal').classList.add('hidden');}catch(err){$('modal-error').textContent=err.message;}};}
  $('modal-close').onclick=()=>$('modal').classList.add('hidden');$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.add('hidden')};
  function showCommunityModal(edit=false){const c=edit?state.community:null;showModal(edit?'Editar comunidade':'Criar comunidade',`<label>Nome<input name="name" required minlength="2" maxlength="80" value="${esc(c?.name||'')}" placeholder="Clube dos amigos"></label><label>Descrição<textarea name="description" maxlength="240" placeholder="Sobre esta comunidade">${esc(c?.description||'')}</textarea></label><label>URL da imagem / thumbnail (HTTPS)<input name="imageUrl" type="url" value="${esc(c?.image_url||'')}" placeholder="https://.../capa.png"></label>`,async v=>{if(edit){const d=await api(`/api/communities/${c.id}`,{method:'PATCH',body:JSON.stringify(v)});state.community=d.community;state.communities=state.communities.map(x=>String(x.id)===String(c.id)?d.community:x);}else{const d=await api('/api/communities',{method:'POST',body:JSON.stringify(v)});state.communities.push(d.community);state.community=d.community;state.channel=null;}renderServers();await loadStructure();});}
  function showProfileModal(){const u=state.user||{};showModal('Editar perfil',`<label>Nome de exibição<input name="username" required minlength="3" maxlength="32" value="${esc(u.username||'')}"></label><label>Descrição<textarea name="description" maxlength="240" placeholder="Conte algo sobre você">${esc(u.description||'')}</textarea></label><label>URL da foto de perfil (HTTPS)<input name="avatarUrl" type="url" maxlength="1000" value="${esc(u.avatar_url||'')}" placeholder="https://.../foto.jpg"></label><p class="tiny">Use uma imagem HTTPS pública. A foto e a descrição ficam salvas na sua conta.</p>`,async v=>{const d=await api('/api/profile',{method:'PATCH',body:JSON.stringify(v)});state.user={...state.user,...d.user};renderProfile();toast('Perfil atualizado!');});}
  async function showInviteModal(){if(!state.community)return toast('Crie ou selecione uma comunidade primeiro.');const d=await api(`/api/communities/${state.community.id}/invites`,{method:'POST',body:'{}'});const url=`${location.origin}${location.pathname}?invite=${encodeURIComponent(d.token)}`;showModal('Convidar pessoas',`<p>Compartilhe este link para convidar alguém para <b>${esc(state.community.name)}</b>. O link expira em 7 dias.</p><label>Link de convite<input id="invite-link" name="inviteLink" readonly value="${esc(url)}"></label><button type="button" class="primary full" id="copy-invite">Copiar link</button>`,async()=>{});setTimeout(()=>$('copy-invite')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(url);toast('Link copiado!');}catch{$('invite-link').select();document.execCommand('copy');toast('Link copiado!');}}),0);}
  async function acceptInvite(token){try{const d=await api(`/api/invites/${encodeURIComponent(token)}`);if(!confirm(`Entrar na comunidade “${d.community.name}”?`))return;await api(`/api/invites/${encodeURIComponent(token)}/join`,{method:'POST',body:'{}'});history.replaceState({},'',location.pathname);state.inviteToken=null;state.community=null;await loadCommunities();toast(`Você entrou em ${d.community.name}!`);}catch(e){toast(e.message);}}
  function showCategoryModal(){if(!state.community)return showCommunityModal();showModal('Criar categoria','<label>Nome da categoria<input name="name" required maxlength="80" placeholder="Jogos, conversas…"></label>',async v=>{await api(`/api/communities/${state.community.id}/categories`,{method:'POST',body:JSON.stringify(v)});await loadStructure();});}
  function showChannelModal(categoryId=''){if(!state.community)return showCommunityModal();const opts=state.categories.map(c=>`<option value="${c.id}" ${String(c.id)===String(categoryId)?'selected':''}>${esc(c.name)}</option>`).join('');showModal('Criar canal',`<label>Nome do canal<input name="name" required maxlength="80" placeholder="geral"></label><label>Tipo<select name="type"><option value="text"># Canal de texto</option><option value="voice">◖)) Canal de voz</option></select></label><label>Categoria<select name="categoryId"><option value="">Sem categoria</option>${opts}</select></label><label>Tópico (opcional)<input name="topic" maxlength="240" placeholder="Sobre o que é este canal?"></label>`,async v=>{await api(`/api/communities/${state.community.id}/channels`,{method:'POST',body:JSON.stringify(v)});await loadStructure();});}
  $('new-community').onclick=()=>showCommunityModal();$('edit-community').onclick=()=>showCommunityModal(true);$('invite-community').onclick=()=>showInviteModal().catch(e=>toast(e.message));$('profile-open').onclick=showProfileModal;$('add-category').onclick=showCategoryModal;$('add-channel').onclick=()=>showChannelModal();
  // WebRTC peer-to-peer voice. A TURN server may be needed for users behind restrictive NATs.
  function makePeer(id){if(state.peers.has(id))return state.peers.get(id);const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]});state.peers.set(id,pc);if(state.voiceStream)state.voiceStream.getTracks().forEach(t=>pc.addTrack(t,state.voiceStream));pc.onicecandidate=e=>{if(e.candidate)state.socket.emit('voice-signal',{channelId:String(state.voiceChannel),to:id,signal:{type:'candidate',candidate:e.candidate}});};pc.ontrack=e=>{let audio=document.getElementById(`audio-${id}`);if(!audio){audio=document.createElement('audio');audio.id=`audio-${id}`;audio.autoplay=true;audio.playsInline=true;$('voice-audio').appendChild(audio);}audio.srcObject=e.streams[0];audio.play().catch(()=>{});monitorSpeaking(id,e.streams[0]);};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState))setSpeaking(id,false);};return pc;}
  async function makeOffer(id){try{const pc=makePeer(id);const offer=await pc.createOffer();await pc.setLocalDescription(offer);state.socket.emit('voice-signal',{channelId:String(state.voiceChannel),to:id,signal:{type:'description',description:pc.localDescription}});}catch(e){console.error('offer voice',e);}}
  async function handleVoiceSignal(data){try{if(!state.voiceChannel||!data?.from)return;state.peerUsers.set(data.from,data.user||{username:'Amigo'});const pc=makePeer(data.from),sig=data.signal||{};if(sig.type==='description'){await pc.setRemoteDescription(sig.description);if(sig.description.type==='offer'){const answer=await pc.createAnswer();await pc.setLocalDescription(answer);state.socket.emit('voice-signal',{channelId:String(state.voiceChannel),to:data.from,signal:{type:'description',description:pc.localDescription}});}}else if(sig.type==='candidate'&&sig.candidate){try{await pc.addIceCandidate(sig.candidate);}catch{}}renderVoiceMembers();}catch(e){console.error('voice signal',e);}}
  $('join-voice').onclick=async()=>{if(!state.channel||state.channel.type!=='voice'||!state.socket)return toast('Conexão de voz indisponível.');if(!navigator.mediaDevices?.getUserMedia)return toast('Seu navegador não liberou o microfone. Use HTTPS e permita o acesso.');try{state.voiceStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});state.voiceChannel=String(state.channel.id);state.socket.emit('join-voice',state.voiceChannel);$('join-voice').disabled=true;$('leave-voice').disabled=false;$('mute-voice').disabled=false;renderVoiceMembers();toast('Você entrou na chamada.');}catch(e){toast('Não foi possível acessar o microfone: '+e.message);}};
  $('mute-voice').onclick=()=>{if(!state.voiceStream)return;state.muted=!state.muted;state.voiceStream.getAudioTracks().forEach(t=>t.enabled=!state.muted);$('mute-voice').textContent=state.muted?'Ativar microfone':'Desativar microfone';};
  function leaveVoice(){if(state.voiceChannel&&state.socket)state.socket.emit('leave-voice');if(state.voiceStream)state.voiceStream.getTracks().forEach(t=>t.stop());state.voiceStream=null;state.voiceChannel=null;state.muted=false;for(const id of [...state.peers.keys()])removePeer(id);if(state.speakingTimer)clearInterval(state.speakingTimer);state.speakingTimer=null;if(state.audioContext){state.audioContext.close().catch(()=>{});state.audioContext=null;}if($('join-voice'))$('join-voice').disabled=false;if($('leave-voice'))$('leave-voice').disabled=true;if($('mute-voice')){$('mute-voice').disabled=true;$('mute-voice').textContent='Microfone desligado';}if($('voice-members'))$('voice-members').innerHTML='<div class="voice-empty">Você saiu da sala.</div>';}
  $('leave-voice').onclick=leaveVoice;
  function renderVoiceMembers(){if(!state.voiceChannel)return;const members=[{id:'self',username:state.user.username,avatar_url:state.user.avatar_url||'',self:true},...Array.from(state.peerUsers.entries()).map(([id,u])=>({id,username:u.username,avatar_url:u.avatar_url||''}))];$('voice-members').innerHTML=members.map(m=>`<div class="voice-member ${m.self?'self':''}" id="voice-member-${esc(m.id)}">${avatarHtml(m.avatar_url,m.username,'voice-avatar')}<b>${esc(m.username)}${m.self?' (você)':''}</b><small>${m.self?(state.muted?'microfone desligado':'microfone ligado'):'conectado'}</small></div>`).join('');}
  function setSpeaking(id,yes){const el=document.getElementById(`voice-member-${id}`);if(el)el.classList.toggle('speaking',!!yes);}
  function monitorSpeaking(id,stream){try{if(!state.audioContext)state.audioContext=new AudioContext();const source=state.audioContext.createMediaStreamSource(stream),analyser=state.audioContext.createAnalyser();analyser.fftSize=512;source.connect(analyser);const data=new Uint8Array(analyser.frequencyBinCount);const tick=()=>{if(!state.peers.has(id))return;analyser.getByteFrequencyData(data);let total=0;for(const v of data)total+=v;setSpeaking(id,total/data.length>13);requestAnimationFrame(tick);};tick();}catch(e){console.debug('speaking meter unavailable',e);}}
  function removePeer(id){const pc=state.peers.get(id);if(pc)pc.close();state.peers.delete(id);state.peerUsers.delete(id);document.getElementById(`audio-${id}`)?.remove();document.getElementById(`voice-member-${id}`)?.remove();}
  $('attach').onclick=()=>toast('Envio de anexos ainda não implementado.');
  const script=document.createElement('script');script.src=API+'/socket.io/socket.io.js';script.onload=()=>{if(state.user)connectSocket();};script.onerror=()=>{};document.head.appendChild(script);
  boot().catch(err=>toast(err.message));
})();
